### PR TITLE
This contains the HTML formatting enhancements that I added to the …

### PR DESCRIPTION
**Pull request by quaxquax**
... enumeration calls, in order to make for a visually more appealing presentation when demoing the quantum-fog software in Jupyter. I.e. all the output features aim at Jupyter and are of limited use in any other environment.

The changes augment the output functionality that was already there. I.e. none of the original text only print features have been changed by me. I just added a bunch of parameters to branch into my new output code. The focus was to get proper HTML tables displayed in Jupyter with formatting of the potential values in order to make this easier on the eye when presenting the software.

### CODE REVIEW

**Comment by rrtucci** [comment]
I still don't know now to use git too well, so it will take me a while to figure out how to incorporateyour changes properly. I might also do some cosmeticchanges to your changes, especially to the docstrings, to preserve the "numpy" styledoc strings. So, how about if we get this compilerdone first, since we are already so close to finishing it,and then we'll deal with the qfog changes later--- notifications@github.com wrote: IFrom: Henning Dekant <notifications@github.com>To: artiste-qb-net/quantum-fog <quantum-fog@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Subject: [artiste-qb-net/quantum-fog] This contains the HTML formatting enhancements that I added to the … (#12)Date: Thu, 29 Dec 2016 23:28:21 -0800... enumeration calls, in order to make for a visually more appealing presentation when demoing the quantum-fog in Jupyter. I.e. all the output features aim at Jupyter and are of limited use in any other environment.
The changes augment the output functionality that was already there. I.e. none of the original text only print features have been changed by me. I just added a bunch of parameters to branch into my new output code. The focus was to get proper HTML tables displayed in Jupyter with formatting of the potential values in order to make this easier on the eye when presenting the software.



You can view, comment on, or merge this pull request online at:
  https://github.com/artiste-qb-net/quantum-fog/pull/12

Commit Summary

  This contains the HTML formating enhancements that I added to the Enumeration calls, in order to make for a visually more appealing presentation when demoing the qfog in jupyter.


File Changes

  
    M
    examples_cbnets/Monty_Hall.bif
    (6)
  
  
    M
    examples_cbnets/Monty_Hall.dot
    (6)
  
  
    A
    examples_cbnets/Monty_Hall.txt
    (28)
  
  
    M
    examples_cbnets/asia.bif
    (32)
  
  
    A
    examples_cbnets/asia.dot
    (18)
  
  
    A
    examples_cbnets/earthquake.dot
    (11)
  
  
    A
    examples_cbnets/student.bif
    (39)
  
  
    A
    examples_cbnets/student.dot
    (11)
  
  
    A
    examples_cbnets/student_broken.bif
    (39)
  
  
    A
    examples_qbnets/QuWetGrass.dot
    (10)
  
  
    M
    examples_qbnets/QuWetGrass.py
    (6)
  
  
    A
    examples_qbnets/YoungDoubleSlit.bif
    (32)
  
  
    A
    examples_qbnets/YoungDoubleSlit.dot
    (10)
  
  
    A
    examples_qbnets/YoungDoubleSlit_test.bif
    (32)
  
  
    M
    inference/EnumerationEngine.py
    (134)
  
  
    M
    inference/InferenceEngine.py
    (58)
  
  
    A
    jupyter-notebooks/Demo_Notebook-Copy1.ipynb
    (1534)
  
  
    A
    jupyter-notebooks/Demo_Notebook-Master-Backup.ipynb
    (3879)
  
  
    A
    jupyter-notebooks/Demo_Notebook-Master-Copy1.ipynb
    (3651)
  
  
    A
    jupyter-notebooks/Demo_Notebook-Master-Copy2.ipynb
    (3819)
  
  
    A
    jupyter-notebooks/Demo_Notebook-Master.ipynb
    (3788)
  
  
    A
    jupyter-notebooks/Demo_Notebook.ipynb
    (773)
  
  
    A
    jupyter-notebooks/Least_action_principle.svg
    (113)
  
  
    A
    jupyter-notebooks/Richard-Feynman.jpg
    (0)
  
  
    A
    jupyter-notebooks/Scratchpad.ipynb
    (150)
  
  
    A
    jupyter-notebooks/Two-Slit_Experiment_Approximation.svg
    (146)
  
  
    A
    jupyter-notebooks/X-Mess_Monty_Hall.png
    (0)
  
  
    A
    jupyter-notebooks/ezvis3d_test-Copy1.ipynb
    (628)
  
  
    A
    jupyter-notebooks/ezvis3d_test.ipynb
    (468)
  
  
    M
    jupyter-notebooks/plotting-density-matrix.ipynb
    (57)
  
  
    A
    jupyter-notebooks/saved/plot_20161215_165908.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161215_170657.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161215_171734.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161215_171848.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161215_171927.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161215_200330.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161215_200622.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161215_201415.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161215_201529.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161215_202153.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161215_202355.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161215_202948.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161215_204104.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161215_204540.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161215_204627.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161215_213057.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161215_213135.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161215_213334.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161215_213413.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161215_213512.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161215_213559.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161215_213730.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161215_215522.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161215_215738.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161215_215832.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161215_220823.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161215_220949.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161216_014858.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161216_194125.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161216_195800.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161216_195835.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161216_201202.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161216_203031.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161216_203131.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161216_203634.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161216_203744.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161216_204728.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161216_204932.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161216_205205.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161216_220749.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161216_221015.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161216_221220.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161216_221518.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161216_221703.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161217_015213.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161217_190554.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161218_231121.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161219_004300.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161219_010642.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161219_012003.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161219_014736.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161219_015045.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161219_015231.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161219_020549.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161219_031413.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161219_031442.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161219_031538.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161219_031625.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161219_034036.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161219_034229.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161219_042120.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161219_195051.html
    (62)
  
  
    A
    jupyter-notebooks/saved/plot_20161219_224224.html
    (62)
  
  
    A
    jupyter-notebooks/still_interference_dots_smear_boxes.jpg
    (0)
  
  
    A
    testing/monty.py
    (50)
  
  
    A
    testing/student_cbnet.py
    (36)
  


Patch Links:

  https://github.com/artiste-qb-net/quantum-fog/pull/12.patch
  https://github.com/artiste-qb-net/quantum-fog/pull/12.diff

**Comment by rrtucci** [comment]
Could you please update your pull request with the following changes?
(1) these files seem to be unnecessary noise:
student_broken.bif
Monty_Hall.txt
YoungDoubleSlit_test.bif
(2) I think the changes you made to the following file are testing junk Am I wrong?
QuWetGrass.py
(3) could you please put all your meetup stuff in a separate folder inside the Jupyter folder called
Dekant-talk-at-Meetup-Dec-19-2016
(4) the new folder called "testing" is unnecessary.Maybe you can put its two files inside the new meetup folder

**Comment by quaxquax** [comment]
Take another look I think everything should be cleaned up now as you requested.

**Comment by quaxquax** [comment]
Bob, I guess I could just go ahead and push the merge button myself, but I figure you should have the honours :-)

My juypyter notebook shows up fine now. It seems that Pycharm somehow messes with the underlying JSON, while the jupyter server can still display and repair it, the viewers just crash.

**Comment by rrtucci** [comment]
I push the red button, specially with so many changes!. Balance of merge powers.There are a few more cosmetic changes that I want to make.You can go ahead and post the notebook at the meetup site with link to the jupyter public viewer. If you are in such a hurry, that is quite adequate for meetup members, theywon't want to run it themselves unless they are really commited,in which case they will ask us for instructions--- notifications@github.com wrote:From: Henning Dekant <notifications@github.com>To: artiste-qb-net/quantum-fog <quantum-fog@noreply.github.com>Cc: "Robert R. Tucci" <tucci@ar-tiste.com>,  Comment <comment@noreply.github.com>Subject: Re: [artiste-qb-net/quantum-fog] This contains the HTML formatting enhancements that I added to the … (#12)Date: Tue, 31 Jan 2017 10:36:22 -0800Bob, I guess I could just go ahead and push the merge button myself, but I figure you should have the honours :-)
My juypyter notebook shows up fine now. It seems that Pycharm somehow messes with the underlying JSON, while the jupyter server can still display and repair it, the viewers just crash.

**Pull request merged**
